--- # Passive Perception Pipeline
# just a mental note so far, ignore this file
- name:       NormalEstimation
  input:      shoulder_cloud
  output:     
    - shoulder_cloud_normals
  parameters: 
    - k: 30
      someotherthing: blabla

- name:       PlanarEstimation
  input:      shoulder_cloud_normals
  parameters:
    - algorithms: 
      - floor_ceiling:
        output: 
      - wall_detection:
        output: shoulder_cloud_walls 
      - table_detection:
        output: shoulder_cloud_tables
      - furniture_detection:
        output: shoulder_cloud_furniture
 
- name:       SupportedStructures
  input:      shoulder_cloud_furniture
  parameters:
    - fit_shapes:
      - lines
                   

